test
actimeo/simmage-ui pull request #124
Opened 2017-01-03 09:07 UTC by stevenribette

2017-01-04 08:08 UTC, actimeo requested changes

2017-01-04 08:08 UTC, actimeo commented on src/app/admin/admin-center/admin-center.component.css
> +.app-toolbar
Il vaut mieux passer par les thèmes du material design pour les couleurs de ces éléments : https://material.angular.io/guide/theming

2017-01-04 08:08 UTC, actimeo commented on src/app/admin/topics/topics-center/topics.component.css
> +.content-toolbar
Idem ici, utiliser les thèmes material

2017-01-04 08:08 UTC, actimeo commented on src/app/shared/select-icon/select-icon.component.ts
> +  <img title="{{icon}}" *ngFor="let icon of icons" src="/assets/icons/{{family}}/{{icon}}.png" (click)="dialogRef.close(icon)">
ok

2017-01-04 08:08 UTC, actimeo commented on src/index.html
> +  <app-root><div id="circle">...</div></app-root>
ok

2017-01-04 08:08 UTC, actimeo commented on src/styles.scss
> +}
- placer le contenu dans un fichier spécifique (voir SMACSS).

- mets les commentaires et noms de variable (tourne) en anglais stp

2017-01-09 08:05 UTC, feloy requested changes

2017-01-09 08:05 UTC, feloy commented on src/app/admin/usergroups/usergroups-center/usergroups.component.css
> +*/
Pourquoi ?

2017-01-09 08:05 UTC, feloy commented on src/app/admin/documents-types/documents-types-form/documents-types-form.component.ts
> +
Tu peux supprimer ces commentaires

2017-01-09 08:05 UTC, feloy commented on src/styles/module/form.scss
> +}
A améliorer

2017-01-09 08:05 UTC, feloy commented on src/app/db-models/organ.ts
> +
Tu peux supprimer

2017-01-10 09:34 UTC, merged